class Appstring {
  static String appname = "Mediapp",
      bestDocapp = "Best Doctor\n Appointment App",
      wellcomeBack = "welcome BAck!",
      WaAreExcited ="Signup now and start exploring all that our app has to offer",
      fullname = "Enter your name",
      email = "emial",
      emailHint = "Enter your email...",
      password = "enter your password",
      paswordHint = "Enter your password here...",
      confirmPassword = "Confirm Password",
      forgotpassword = "forgot_PAsssword?",
      login = "Login",
      Signup = "signup",
      welcome = "welcome",
      search = "search Doctor",
      alreadyHaveAccount = "Already have an Account?",
      dontHaveAccount = "don't have an account?",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lung = "Lungs",
      heart = "Hearts",
      kidney = "Kidney",
      changepassword = "Change Password",
      termCondition = "Term Condition",
      Signout = "SignOut";
}
