// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFbItdpTnleW4SsXKkcS8Assn0AiD_qM',
    appId: '1:971822085534:web:bdc5eaad1829695d5f128f',
    messagingSenderId: '971822085534',
    projectId: 'mediapp-a6c9d',
    authDomain: 'mediapp-a6c9d.firebaseapp.com',
    storageBucket: 'mediapp-a6c9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRcXDR1GRuNL-UUeveoIbBZ_KlpFNGFk',
    appId: '1:971822085534:android:d915f2ff3d06fe365f128f',
    messagingSenderId: '971822085534',
    projectId: 'mediapp-a6c9d',
    storageBucket: 'mediapp-a6c9d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-1pjEq5AKw_dgsVJef0ZuAHPa7VNo8O0',
    appId: '1:971822085534:ios:9866e825164f12225f128f',
    messagingSenderId: '971822085534',
    projectId: 'mediapp-a6c9d',
    storageBucket: 'mediapp-a6c9d.appspot.com',
    iosBundleId: 'com.example.doctorAppointment.RunnerTests',
  );
}
